import{_ as u}from"./CzL0xrjJ.js";import{S as P}from"./YIQM4wyO.js";import v from"./CwYUTAUm.js";import{d as q,u as h,c as p,f as o,t,e as s,F as m,k as b,b as d,o as a,l as $,R as f,h as B}from"./Ce7G41BA.js";import{u as k}from"./CSrWLnnC.js";import"./CwqYXxsh.js";import"./CPbcXw8J.js";import"./BTW5NWG2.js";import"./DIY7DJCO.js";const S={class:"provide-page"},y={class:"provide-page__wrapper"},w={class:"provide-page__head"},I={class:"provide-page__container"},R={class:"provide-page__title heading-x-large"},x={class:"provide-page__description body-large"},C={class:"provide-page__top-banner"},E={class:"provide-page__top-banner-text"},T={class:"heading-medium"},U={class:"subtitle-medium"},F={class:"provide-page__instruction"},L={class:"provide-page__container"},N={class:"provide-page__subtitle heading-large"},V={class:"provide-page__steps"},z={class:"provide-page__result"},D={class:"provide-page__faq"},M={class:"provide-page__bottom-banner"},O={class:"provide-page__container"},Q={class:"provide-page__bottom-banner-text"},W={class:"subtitle-large"},j={class:"subtitle-large"},A=q({__name:"provide-sim-cards-with-smartphones",setup(G){const{t:e,tm:n}=h(),l=[{label:e("ProvidePage.questions.question1.label"),content:`
      <ul>
        <li>
          ${e("ProvidePage.questions.question1.item1")}
        </li>
        <li>
          ${e("ProvidePage.questions.question1.item2")}
        </li>
        <li>
          ${e("ProvidePage.questions.question1.item3")}
        </li>
        <li>
          ${e("ProvidePage.questions.question1.item4")}
        </li>
      </ul>
      <p>
        ${e("ProvidePage.questions.question1.paragraph")}
      </p>`},{label:e("ProvidePage.questions.question2.label"),content:`
      <p>
        ${e("ProvidePage.questions.question2.paragraph")}
      </p>`},{label:e("ProvidePage.questions.question3.label"),content:`
      <p>
        ${e("ProvidePage.questions.question3.paragraph")}
      </p>`},{label:e("ProvidePage.questions.question4.label"),content:`
      <p>
        ${e("ProvidePage.questions.question4.paragraph1")}
      </p>
      <ol>
        <li>
          ${e("ProvidePage.questions.question4.item1")}
        </li>
        <li>
          ${e("ProvidePage.questions.question4.item2")}
        </li>
      </ol>
      <p>
        ${e("ProvidePage.questions.question4.paragraph2")}
      </p>`},{label:e("ProvidePage.questions.question5.label"),content:`
      <p>
        ${e("ProvidePage.questions.question5.paragraph1")}
      </p>
      <ol>
        <li>
          ${e("ProvidePage.questions.question5.item1")}
        </li>
        <li>
          ${e("ProvidePage.questions.question5.item2")}
        </li>
      </ol>
      <p>
        ${e("ProvidePage.questions.question5.paragraph2")}
      </p>`},{label:e("ProvidePage.questions.question6.label"),content:`
      <p>
        ${e("ProvidePage.questions.question6.paragraph")}
      </p>`},{label:e("ProvidePage.questions.question7.label"),content:`
      <p>
        ${e("ProvidePage.questions.question7.paragraph")}
      </p>`},{label:e("ProvidePage.questions.question8.label"),content:`
      <p>
        ${e("ProvidePage.questions.question8.paragraph")}
      </p>`}],_=()=>{window.open(f.SUPPLIER,"_blank")};return k({title:n("ProvidePage.meta.title"),description:n("ProvidePage.meta.description")}),(r,H)=>{const c=u;return a(),p("div",S,[o("div",y,[o("section",w,[o("div",I,[o("h1",R,t(s(e)("ProvidePage.title")),1),o("p",x,t(s(e)("ProvidePage.description")),1),o("div",C,[o("div",E,[o("p",T,t(s(e)("ProvidePage.topBanner.paragraph1")),1),o("p",U,t(s(e)("ProvidePage.topBanner.paragraph2")),1)])])])]),o("section",F,[o("div",L,[o("h2",N,t(s(e)("ProvidePage.subtitle")),1),o("div",V,[(a(!0),p(m,null,b(r.$tm("ProvidePage.steps"),(g,i)=>(a(),$(P,{key:i,index:i,step:g,"description-key":`ProvidePage.steps.${i}.description`,"heading-tag":"h3"},null,8,["index","step","description-key"]))),128))]),o("div",z,[o("p",null,t(s(e)("ProvidePage.result")),1),d(c,{size:"lg",label:r.$t("ProvidePage.btn"),class:"provide-page__result-btn",onClick:_},null,8,["label"])])])]),o("div",D,[d(v,{title:s(e)("ProvidePage.faq"),questions:l},null,8,["title"])]),o("div",M,[o("div",O,[o("div",Q,[o("p",W,t(s(e)("ProvidePage.bottomBanner.paragraph1")),1),o("p",j,t(s(e)("ProvidePage.bottomBanner.paragraph2")),1)])])])])])}}}),ie=B(A,[["__scopeId","data-v-36ba05cc"]]);export{ie as default};
